name: Vote App Build

on:
  push:
    paths:
    - 'vote/**'
    branches: [ master ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        registry: public.ecr.aws
      env:
        AWS_REGION: eu-east-1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: public.ecr.aws/y8r3s1k5
        ECR_REPOSITORY: votingapp-vote
      run: |
        # Build a docker container and push it to ECR 
        docker build -f ./vote/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} ./vote
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
